export declare const CHAT_SERVER = "irc-ws.chat.twitch.tv";
export declare const CHAT_SERVER_PORT = 6667;
export declare const CHAT_SERVER_SSL_PORT = 443;
export declare const CONNECTION_TIMEOUT = 5000;
export declare const KEEP_ALIVE_PING_TIMEOUT = 150000;
export declare const KEEP_ALIVE_RECONNECT_TIMEOUT = 200000;
export declare const JOIN_TIMEOUT = 1000;
export declare const COMMAND_TIMEOUT = 1000;
export declare const CLIENT_PRIORITY = 100;
export declare const RATE_LIMIT_USER = 20;
export declare const RATE_LIMIT_MODERATOR = 100;
export declare const RATE_LIMIT_KNOWN_BOT = 50;
export declare const RATE_LIMIT_VERIFIED_BOT = 7500;
export declare const ERROR_CONNECT_TIMED_OUT = "ERROR: connect timed out";
export declare const ERROR_CONNECTION_IN_PROGRESS = "ERROR: connection in progress";
export declare const ERROR_JOIN_TIMED_OUT = "ERROR: join timed out";
export declare const ERROR_SAY_TIMED_OUT = "ERROR: say timed out";
export declare const ERROR_COMMAND_TIMED_OUT = "ERROR: command timed out";
export declare const ERROR_COMMAND_UNRECOGNIZED = "ERROR: command unrecognized";
export declare const ERROR_PART_TIMED_OUT = "ERROR: part timed out";
export declare const MESSAGE_PARAMETER_PREFIX = "msgParam";
export declare const MESSAGE_PARAMETER_PREFIX_RE: RegExp;
export declare const PRIVATE_MESSAGE_HOSTED_RE: RegExp;
export declare const ANONYMOUS_USERNAME = "justinfan";
export declare const ANONYMOUS_USERNAME_RE: RegExp;
